name: 'Google Cloud resources "Deploy code" Action'
description: 'This Github action can be used to deploy source code to GCP resources like Cloud Functions.'
author: 'Chaitanya Pusuluri'
inputs:
  gcp_project:
    description: 'The name of the GCP project you want to deploy'
    required: true
  gcp_region:
    description: 'GCP region where the cloud function is hosted'
    required: true
  cloud_function_name:
    description: 'Name of the cloud function in GCP'
    required: true
  cloud_function_directory:
    description: 'The directory in your repository where are you storing the code files for cloud function'
    required: true
  credentials:
    description: 'Service account to authenticate with BigQuery'
    required: true
  debug_mode:
    description: 'Enable debug mode'
    required: false
  token:
    description: 'Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "GCP_PROJECT=${{ inputs.gcp_project }}" >> $GITHUB_ENV
        echo "GCP_REGION=${{ inputs.gcp_region }}" >> $GITHUB_ENV
        echo "CLOUD_FUNCTION_NAME=${{ inputs.cloud_function_name }}" >> $GITHUB_ENV
        echo "CLOUD_FUNCTION_DIRECTORY=${{ inputs.cloud_function_directory }}" >> $GITHUB_ENV
        echo "CREDENTIALS=${{ inputs.credentials }}" >> $GITHUB_ENV
        echo "DEBUG_MODE=${{ inputs.debug_mode }}" >> $GITHUB_ENV
        echo "TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: print_env
      run: python src/print_env.py
      shell: bash