name: 'Google-Cloud-Functions-Deploy-Source-Code-Action'
description: 'This Github action can be used to deploy source code to GCP Cloud Functions.'
author: 'Chaitanya Pusuluri'
branding:
  icon: upload-cloud
  color: yellow
inputs:
  gcp_project:
    description: 'Name of the project in GCP'
    required: true
  gcp_region:
    description: 'Name of the region in GCP'
    required: true
  cloud_function_name:
    description: 'Name of the cloud function in GCP'
    required: true
  source_code_directory:
    description: 'The directory in your repository where are you storing the code files for cloud function'
    required: true
  credentials:
    description: 'Service account to authenticate with cloud storage to upload source code'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r ./requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "GCP_PROJECT=${{ inputs.gcp_project }}" >> $GITHUB_ENV
        echo "GCP_REGION=${{ inputs.gcp_region }}" >> $GITHUB_ENV
        echo "CLOUD_FUNCTION_NAME=${{ inputs.cloud_function_name }}" >> $GITHUB_ENV
        echo "SOURCE_CODE_DIRECTORY=${{ inputs.source_code_directory }}" >> $GITHUB_ENV
        echo "CREDENTIALS=${{ inputs.credentials }}" >> $GITHUB_ENV
      shell: bash
    - name: Push Source Code to Google Cloud Function
      id: patch_cloud_function_source_code
      run: python src/patch_cloud_function_source_code.py
      shell: bash