name: patch-cloud-function
on: [workflow_dispatch]

jobs:
  patch-cloud-function:
    runs-on: ubuntu-latest
    name: Pushes the source code into Google Cloud Storage and Patches a Cloud Function with source code update.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Source Code to Cloud Storage and Patch the cloud function
        id: print_env_vars
        uses: ./.github/actions/patch_cloud_function_source_code
        with:
          gcp_project: gcp_project_test
          gcp_region: gcp_region_test
          cloud_function_name: cloud_function_name_test
          cloud_function_directory: cloud_function_directory_test
          credentials: credentials_test
          debug_mode: debug_mode_test
          token: ${{ secrets.TOKEN }}
      #- name: Print the square
      #  run: echo "${{ steps.get_square.outputs.num_squared }}"