name: Print env vars
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Prints the env vars
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print env vars
        id: get_square
        uses: ./.github/actions/print_env # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          gcp_project: gcp_project_test
          gcp_region: gcp_region_test
          cloud_function_name: cloud_function_name_test
          cloud_function_directory: cloud_function_directory_test
          credentials: credentials_test
          debug_mode: debug_mode_test
          token: ${{ secrets.TOKEN }}
      #- name: Print the square
      #  run: echo "${{ steps.get_square.outputs.num_squared }}"